### ISSUE TITLE
1.16.0 - Chrome Disabled Extension because it wants to read and change browsing history?

### ISSUE THREAD

**Issue by AwesomeShare** [xcv58/Tab-Manager-v2#1408]
Chome just installed version 1.16.0, but Chrome automatically disables the extension because it wants to "Read and change your browsing history".

Is it safe to accept these new permissions?  The chrome store page doesn't say anything about v1.16.0 (changelog).

**Comment by xcv58** [comment]
Yes, it's safe to accept the new permission (only `history` is added). 

It's for this feature request: https://github.com/xcv58/Tab-Manager-v2/issues/1399

You can see the screenshot of the new feature here:
https://github.com/xcv58/Tab-Manager-v2/blob/master/packages/integration_test/test/__image_snapshots__/extension-test-ts-the-extension-page-should-support-search-browser-history-3-snap.png
https://github.com/xcv58/Tab-Manager-v2/blob/master/packages/integration_test/test/__image_snapshots__/extension-test-ts-the-extension-page-should-support-search-browser-history-2-snap.png

Sorry I didn't get a chance to update the description since the release is automated. I will update the description in a few hours.

In the meanwhile, you can find the changelog and source code: https://tab-manager.vercel.app/?path=/story/changelog--page
