### ISSUE TITLE
More than 11 columns without scrolling? 

### ISSUE THREAD

**Issue by msg43** [xcv58/Tab-Manager-v2#2290]
Is it possible for me to set how many columns I want to have without scrolling?  I tend to use A LOT of tabs.  So even with 11 columns I end up scrolling.  When I stretch the Tab Manager V2 window it doesn't remove the scrolling, it just makes the columns wider.  Is there a way to give the user control of whether to make the columns wider or to show more columns at one time?  

Thanks!!

**Comment by xcv58** [comment]
There is no direct way to do it. But you can set the `Minimum Tab Width` option to a smaller value so that each column will be narrow so that the window can fit more columns.

![image](https://user-images.githubusercontent.com/503123/216499108-fac4e4a4-69c0-4a7f-a6af-ea1ecf924e00.png)



Please let me know whether this solves your problem.

**Comment by xcv58** [comment]
Please reopen this issue if it doesn't work for you.
