### ISSUE TITLE
Extremely poor performance, especially closing tabs

### ISSUE THREAD

**Issue by hackel** [xcv58/Tab-Manager-v2#306]
I *really* love the functionality of this extension.  Unfortunately, the performance is just so poor that it makes it basically difficult to use for daily work.  The biggest issue is closing tabs.

With 346 tabs open, after closing a tab, it takes **21 seconds** before the Tab Manager UI becomes responsive again.  First, the removed tab changes to a blank space in the menu and the UI freezes for 10 seconds, then that gap disappears and it freezes for an additional 11 seconds.  This is on a 2.6 GHz i7-9750H.  It is obviously doing a lot of calculation to re-render of all of my tabs in the list, but it shouldn't take this long.  My guess is that Material-UI is just too heavy for this type of extension.

**Edit:** I just tried this opening the extension in a new tab instead of the drop-down window, and did not experience the issue.  Rerendering the list took less than a second.

You might argue that it's crazy to have that many tabs open, but honestly, if I wasn't a tab hoarder, I would have no use for your amazing extension!

The second issue is the open time.  When I first click the icon, a giant white box appears on screen for approximately one second.  This is quite jarring, particularly since I'm using a dark theme.  Then the UI appears and the individual tabs load progressively over ~10 seconds.  I could understand if this happened the very first time it was opened after starting the browser, but after that this should be cached so that the display is instant.

One idea for making it *seem* a bit faster would be to first load the current tab and 6 tabs before/after it to fill up the display, then progressively backfill the tabs before and after that initial screen.  That would cover 90% of my tab management tasks.  I'm rarely hunting through the entire list, and if I am the search functionality works great.

The third performance issue is related to the animations.  The tooltips have some type of zoom animation applied that just makes the UI feel extremely sluggish.  Even worse, they often do a double-zoom, I'm not sure if that is intentional or the animation is running twice for some reason.  I realize this is just a matter of opinion, but personally I would prioritize performance over looking pretty.  I would either eliminate the animation or replace it with a much faster fade-in, and slightly decrease the time delay before the tooltips appear.

**Desktop:**
 - OS: Ubuntu
 - Browser: Firefox
 - Version 74

**Comment by xcv58** [comment]
Hi @hackel 
Thanks for your feedback.

> The biggest issue is closing tabs.
> The second issue is the open time.

For these two issues, they are eventually the same issue of rendering the tabs.

I usually have 80-150 tabs open on Chrome with MacBook Pro, haven't faced the same issue. Sometimes the UI performance is bad because of the laptop itself is busy to compile code.

I will try this on Firefox with 300 tabs to test the performance.

I spent a ton of effort to optimize the performance, that's why there is progressively rendering and other options like `Show URL`, `Show Tab Tooltip`, `Highlight Duplicated Tabs`. You can try to disable those option to see whether it improve the performance.

> Edit: I just tried this opening the extension in a new tab instead of the drop-down window, and did not experience the issue. Rerendering the list took less than a second.

You can use Ctrl-T (macOS) or Alt+T (linux, linux, chromeOS) to open the extension in a standalone mode to see whether it works.

> The third performance issue is related to the animations.

I assume you are talking about the tab tooltip, not the tooltip for buttons.

I didn't find this happen on the Chrome browser since Firefox is not my primary browser. I'll work on this to figure out what's the root cause.

In the meantime, if you don't need the tooltip, you can disable the feature as a workaround.

**Comment by xcv58** [comment]
> The biggest issue is closing tabs.
This issue happens on Firefox but not Chrome because of the block GC. 

https://github.com/xcv58/Tab-Manager-v2/blob/master/src/js/stores/HoverStore.tsx#L35

![image](https://user-images.githubusercontent.com/503123/75947687-13c38300-5e56-11ea-9f64-be074c5d1220.png)

**Comment by xcv58** [comment]
@hackel just keep you update, I find the root cause of the problem. It's mainly caused by Material UI. And I would gradually replace the Material UI component for the individual tab by #305

On my development, it shows significant performance gain.

**Comment by xcv58** [comment]
@hackel I release v1.5.0 contains several performance improvements. It works smoothly for me on Firefox with 500+ tabs.

![image](https://user-images.githubusercontent.com/503123/76270952-44c7fd00-6234-11ea-8dd3-c9e4345317e5.png)

Could you please give it a try?

**Comment by hackel** [comment]
@xcv58 That's an incredible improvement!  With ~400 tabs open, closing a tab happens in less than 1 second.  Opening now takes ~5 seconds, so that's an improvement as well.  Thanks for solving this!

I've noticed some inconsistency when opening the dropdown.  Most of the time, it still opens to a completely blank white square while loading, but occasionally the main (dark-themed) UI will open with a spinner instead of tabs.  Just now it also opened with a white background with spinner, and then the background changed to dark with the spinner still showing until the full UI rendered.  There must be some obscure race condition happening.

**Comment by xcv58** [comment]
Thanks for your feedback. I'm glad it helps.

> I've noticed some inconsistency when opening the dropdown. Most of the time, it still opens to a completely blank white square while loading, but occasionally the main (dark-themed) UI will open with a spinner instead of tabs. Just now it also opened with a white background with spinner, and then the background changed to dark with the spinner still showing until the full UI rendered. There must be some obscure race condition happening.

For this one, I believe it's caused by the JS query for dark theme. Since I decided to gradually deprecate the Material UI in this repo.

After I finish the deprecation, we can use the css ONLY approach for different themes. It wouldn't be a problem anymore. But the process may be slow and you can see small improvements over time.

**Comment by xcv58** [comment]
Close since I didn't experience similar performance anymore.
