### ISSUE TITLE
larger window without cutting off bottom icons?

### ISSUE THREAD

**Issue by dkapz** [xcv58/Tab-Manager-v2#557]
**Is your feature request related to a problem? Please describe.**
There seems to be a problem with the extension cutting off the bottom row of icons (settings, help, etc) in the viewing window. In addition, it would be nice if the viewing window could be larger to allow for multiple windows of tabs without having to scroll around to to see the tab groups.

**Describe the solution you'd like**
Larger viewing window, not cut off icons.

**Describe alternatives you've considered**

**Additional context**

**Comment by xcv58** [comment]
Thanks for your feedback @dkapz 

> There seems to be a problem with the extension cutting off the bottom row of icons (settings, help, etc) in the viewing window. In addition, it would be nice if the viewing window could be larger to allow for multiple windows of tabs without having to scroll around to to see the tab groups.

Did you open the view via clicking the extension button? 

If yes, it's not possible to expand the size. Because of the extension limitation: https://stackoverflow.com/a/8983678

But we have a workaround for the bottom icons. We can hide the buttons by disabling the "Always Show Toolbar":

![image](https://user-images.githubusercontent.com/503123/87614168-21223100-c6c4-11ea-9629-a125c9e10e45.png)


If it's other issues, could you please share a screenshot if possible?

**Comment by dkapz** [comment]
yes I thought as much about size link limitations being down to chrome /edge!

maybe in future. thanks for the reply!
david

**Comment by xcv58** [comment]
Sorry to mention that, you can use Ctrl+T (masOS) or Option+T (Windows/Linux) to toggle a dedicated window which is clearly larger than the default popup window.
